server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: resource
          uri: http://127.0.0.1:8090/
          predicates:
            - Path=/resource/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/gateway"
            scope: openid
        provider:
          spring:
            issuer-uri: http://localhost:9000